package wrapper

import (
	"context"
	"encoding/json"
	"flag"
	"os"
	"regexp"
	"slices"
	"testing"
	"time"

	"github.com/hollis-labs/agent-contracts-leaf/runtimes"
	"github.com/hollis-labs/go-providers/providertest"
	runtimeevents "github.com/hollis-labs/go-runtime-events/runtimeevents"

	"github.com/hollis-labs/go-agent-wrapper/acp"
	"github.com/hollis-labs/go-agent-wrapper/launch"
)

var updateNativePosture = flag.Bool("update-native-posture", false, "rewrite testdata/native_empty_posture.json from this tree")

// nativeLaunchGolden is what a native launch with no PermissionPosture
// spawned: its argv and the environment entries it added to or changed from
// the test process's, with temporary paths as placeholders.
type nativeLaunchGolden struct {
	Args []string          `json:"args"`
	Env  map[string]string `json:"env"`
}

// postureLaunchCases are the native runtimes' default modes, each with a
// transcript that lets one launch run.
var postureLaunchCases = []struct {
	id    runtimes.ID
	runs  []providertest.Run
	cfg   func(*Config)
	drive func(t *testing.T, w *Wrapper, sink *capturingSink, manager *acp.Manager)
}{
	{runtimes.Claude, []providertest.Run{providertest.Replay("claude/stream_two_turns")}, nil,
		func(t *testing.T, w *Wrapper, sink *capturingSink, _ *acp.Manager) {
			sink.waitFor(t, runtimeevents.KindSessionReady, 5*time.Second)
			for _, text := range []string{"say hi", "say bye"} {
				if err := w.SendInput(context.Background(), []byte(`{"type":"user","message":{"role":"user","content":"`+text+`"}}`)); err != nil {
					t.Fatalf("SendInput: %v", err)
				}
				sink.waitFor(t, runtimeevents.KindTurnCompleted, 5*time.Second)
			}
		}},
	{runtimes.Codex, []providertest.Run{providertest.Script(providertest.RecvLine(), providertest.Exit(0)).When("app-server")},
		func(c *Config) { c.AutoFireFirstTurn = true; c.FirstTurnPayload = "kickoff payload" }, nil},
	{runtimes.OpenCode, []providertest.Run{providertest.Replay("opencode/run_turn1").When("run")}, nil, drivePerTurn},
	{runtimes.Antigravity, []providertest.Run{providertest.Replay("antigravity/print_turn1")}, nil, drivePerTurn},
}

var tempPath = regexp.MustCompile(regexp.QuoteMeta(os.TempDir()) + `/[^/"]+/[0-9]+`)

// A native launch that names no posture spawns exactly what wrapper v0.20.0
// did, before PermissionPosture mapped to launch flags (CW-20260930-0138).
// testdata/native_empty_posture.json was generated by this test, unchanged,
// from a checkout of v0.20.0 (-update-native-posture). Regenerate it only for
// a deliberate argv or environment change.
func TestNativeEmptyPostureMatchesV0_20_0(t *testing.T) {
	skipUnlessSh(t)
	inherited := map[string]bool{}
	for _, kv := range os.Environ() {
		inherited[kv] = true
	}
	got := map[string]nativeLaunchGolden{}
	for _, c := range postureLaunchCases {
		fake := providertest.New(t, c.id, c.runs...)
		runSelected(t, launch.Selection{Runtime: string(c.id), Binary: fake.Path}, c.cfg, c.drive)
		call := fake.Call(0)
		g := nativeLaunchGolden{Env: map[string]string{}}
		for _, a := range call.Args {
			g.Args = append(g.Args, tempPath.ReplaceAllString(a, "<tmp>"))
		}
		for _, kv := range call.Env {
			if inherited[kv] {
				continue
			}
			name, value, _ := cutEnv(kv)
			g.Env[name] = tempPath.ReplaceAllString(value, "<tmp>")
		}
		got[string(c.id)] = g
	}

	const path = "testdata/native_empty_posture.json"
	if *updateNativePosture {
		b, err := json.MarshalIndent(got, "", "  ")
		if err != nil {
			t.Fatal(err)
		}
		if err := os.MkdirAll("testdata", 0o750); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, append(b, '\n'), 0o600); err != nil {
			t.Fatal(err)
		}
		return
	}
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	var want map[string]nativeLaunchGolden
	if err := json.Unmarshal(b, &want); err != nil {
		t.Fatal(err)
	}
	for id, w := range want {
		g := got[id]
		if !slices.Equal(g.Args, w.Args) || !equalEnv(g.Env, w.Env) {
			t.Errorf("%s: an empty posture changed the launch from v0.20.0's:\ngot  %+v\nwant %+v", id, g, w)
		}
	}
	if len(got) != len(want) {
		t.Errorf("golden has %d runtimes, test ran %d", len(want), len(got))
	}
}

func cutEnv(kv string) (string, string, bool) {
	for i := 0; i < len(kv); i++ {
		if kv[i] == '=' {
			return kv[:i], kv[i+1:], true
		}
	}
	return kv, "", false
}

func equalEnv(a, b map[string]string) bool {
	if len(a) != len(b) {
		return false
	}
	for k, v := range a {
		if bv, ok := b[k]; !ok || bv != v {
			return false
		}
	}
	return true
}
